version: "3.9"

services:
  bot:
    build: Bot
    restart: unless-stopped
    volumes:
      - ./Bot/data:/app/data
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      E621_USERNAME: ${E621_USERNAME}
      E621_API_KEY: ${E621_API_KEY}
